---
- |
    CREATE TABLE public.accounts_facebook (
        facebook_id character varying(32) NOT NULL,
        "user" character(12) NOT NULL
    );

- |
    CREATE TABLE public.scenarios (
        id character(12) NOT NULL,
        title character varying(256) NOT NULL,
        description text,
        publisher character(12) NOT NULL,
        version character varying(32) NOT NULL,
        url text NOT NULL,
        is_published boolean NOT NULL,
        updated_at timestamp with time zone NOT NULL
    );

- |
    CREATE TABLE public.session_states (
        session character(12) NOT NULL,
        key character varying(64) NOT NULL,
        value character varying(64) NOT NULL
    );

- |
    CREATE TABLE public.sessions (
        id character(12) NOT NULL,
        "user" character(12) NOT NULL,
        scenario character(12) NOT NULL
    );

- |
    CREATE TABLE public.test (
        key character(10) NOT NULL,
        value integer NOT NULL
    );

- |
    CREATE TABLE public.test_no_prim (
        name character varying(10),
        value character varying(10)
    );

- |
    CREATE TABLE public.users (
        id character(12) NOT NULL,
        display_name character varying(256) NOT NULL
    );

- |
    ALTER TABLE ONLY public.accounts_facebook
        ADD CONSTRAINT account_facebook_pkey PRIMARY KEY (facebook_id);

- |
    ALTER TABLE ONLY public.scenarios
        ADD CONSTRAINT games_pkey PRIMARY KEY (id);

- |
    ALTER TABLE ONLY public.sessions
        ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

- |
    ALTER TABLE ONLY public.test
        ADD CONSTRAINT test_pkey PRIMARY KEY (key);

- |
    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_pkey PRIMARY KEY (id);

- |
    ALTER TABLE ONLY public.accounts_facebook
        ADD CONSTRAINT account_facebook_user_fkey FOREIGN KEY ("user") REFERENCES public.users(id);

- |
    ALTER TABLE ONLY public.scenarios
        ADD CONSTRAINT games_publisher_fkey FOREIGN KEY (publisher) REFERENCES public.users(id);

- |
    ALTER TABLE ONLY public.session_states
        ADD CONSTRAINT session_states_session_fkey FOREIGN KEY (session) REFERENCES public.sessions(id);

- |
    ALTER TABLE ONLY public.sessions
        ADD CONSTRAINT sessions_game_fkey FOREIGN KEY (scenario) REFERENCES public.scenarios(id);

- |
    ALTER TABLE ONLY public.sessions
        ADD CONSTRAINT sessions_user_fkey FOREIGN KEY ("user") REFERENCES public.users(id);

- |
    CREATE TABLE public.current_stages (
        session character(12) NOT NULL,
        stage character varying(64) NOT NULL
    );

- |
    ALTER TABLE ONLY public.current_stages
        ADD CONSTRAINT current_stages_session_fkey FOREIGN KEY (session) REFERENCES public.sessions(id);
